---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-admin-token
  namespace: garage
spec:
  encryptedData:
    admin-token: AgCiDpa5LfkvA1EtMJjNNQg3yduDbV/i36oGLxb+RFXwvyjibTH4L7cG2nhNWlaBe1EfahSrR71Dxdh5ANgtEXjQSKZ8i3erlROU8kGRkaqpE9PbUNdC+4PdZCqFxi/InqtAODpsIuG/Kvff95rZrpORkRCHMzoQjL5tgw8swnBh5yozdDKLnupwqO0+JIF4v5vQkVnJcsHnfLMnerN+EuJvFxeZg0fQpC+8ftGmaLFUB4AKvKducA1iho0kacS3ku7ppZBPVjWkuR5lb2RJv1g6s58H/KZYXGTgdZKaDDPtNfyTPIvbcGBUPEF5oCEMG6CZp2LZQp0Uxb5hvg+MvQsTqlkr5vXIoUyVV/5Xs+Gxpe36j5gwU1vKd9Jrj8e2vS9zNBMKieiXm6g4GoDxriMB4lkixo0pNZCPe6yUB2A0MMxyHWzyfghijP2rX62f9TrgR4H4eQcDH0c36LtJwoWZ3f5Wt/i8LRstAfVU3Wb/PguuWdBPojeQYXMkwlW/nFQ+4b82MeW6OQs7PBO3HtUscwK3IXaA3Vw8oO+bKHPJaLdW512MN1IxNQORuaEZd6YzsFHsC6MOivy97cOkY2mCWwzh+cQO4PFsQzfS5vR8Bvxhj/Pa9SGnSYX7EA08e4b7xhvjYNBHjHzJeVw8vpWaCLMe+1shMa20DhVBY1POlGoeQKv3h4pNxZFP1j1rzQJ/BQSd/gR5ne/ljiFJFNGBlcX7ALzjbgWGioFv/Mt27LX+Q02JIdzrNewHWzqCJ5DS6CYsjo09RMmA2VC5pSCJ
  template:
    metadata:
      name: garage-admin-token
      namespace: garage
    type: Opaque
