apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - pvc.yaml
  - deploy.yaml
  - svc.yaml
  - ingress.yaml
  - cert.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: vaultwarden
