apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/sealed-secrets
  - infra/cert-manager
  - infra/traefik
  - infra/flux

  - namespaces/vaultwarden.yaml
  - apps/vaultwarden

  - namespaces/authentik.yaml
  - apps/authentik

  - apps/grimmory

  - namespaces/shelfmark.yaml
  - apps/shelfmark

  - namespaces/hytale.yaml
  - apps/hytale
