apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  targetNamespace: authentik
  chart:
    spec:
      chart: authentik
      version: "2025.10.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
