apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-mirror
  namespace: crossplane-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cnpg/postgres-superuser
type: Opaque
