apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: db-provider
spec:
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane-system
      name: postgres-superuser-mirror
  sslMode: require
