apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grimmory

resources:
  - namespace.yaml
  - grimmory-sealedSecret.yaml
  - grimmory-deploy.yaml
  - grimmory-svc.yaml
  - grimmory-pvc.yaml
  - mariadb-sealedSecret.yaml
  - mariadb-deploy.yaml
  - mariadb-svc.yaml
  - mariadb-pvc.yaml
  - buffering-middleware.yaml
  - ingressRoute.yaml
