apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
