apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 30m
  targetNamespace: sonarqube
  chart:
    spec:
      chart: sonarqube
      version: ">=2025.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: sonarsource
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sonarqube-values
      valuesKey: values.yaml
