apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-pgloader
  namespace: vaultwarden
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: sqlite-wal-disable
          image: alpine:3.21
          command:
            - sh
            - -ec
            - |
              apk add --no-cache sqlite
              cd /data
              sqlite3 db.sqlite3 'PRAGMA wal_checkpoint(TRUNCATE);'
              sqlite3 db.sqlite3 'PRAGMA journal_mode=DELETE;'
              ls -lah .
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: pgloader
          image: dimitri/pgloader:v3.6.7
          env:
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-pg-creds
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-pg-creds
                  key: password
          command:
            - sh
            - -ec
            - |
              cat > /tmp/bitwarden.load <<EOF
              load database
                from sqlite:///data/db.sqlite3
                into postgresql://${PG_USERNAME}:${PG_PASSWORD}@postgres-rw.cnpg.svc.cluster.local:5432/vaultwarden
                WITH data only, include no drop, reset sequences
                EXCLUDING TABLE NAMES LIKE '__diesel_schema_migrations'
                ALTER SCHEMA 'bitwarden' RENAME TO 'public'
              ;
              EOF
              pgloader /tmp/bitwarden.load
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
