apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

# this version is enforced by longhorn, see https://longhorn.io/docs/1.11.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support
resources:
  - https://github.com/kubernetes-csi/external-snapshotter//client/config/crd?ref=v8.6.0
  - https://github.com/kubernetes-csi/external-snapshotter//deploy/kubernetes/snapshot-controller?ref=v8.6.0
  - snapshot-class.yaml
