---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgCxw68wnIgvT4tah4hqMzTYYeswTIA/1K+AXatZiBAOAmZo9GoaSNbreamvTM/ds9Dtcpy1biCbFA/7mYDGOILiWBklbd2qMjL+T7Rn18F4LaAr8wy+gWGj7NUHW1dpEkhSiX4qtmkIDNnYyhrOVab53yfQpPPXy2uTwZC+BzLnHtWzcTxgjFQ2UDHJMpOKhPJRzcnZtSjHEJCIwYR9sX1lCo/+/jJvDOqeRCaGIELfU+cCoLKABgI/gS9zZG/3/WPVucwwwRwOpI6OZ9TAHJy+dql0jeYSwSQdVCuRh731VEOBONWIG0nUB6mJJnT3vxP/UXC1ByCU9+/S7d0GKqqD78oa90trdve1p0vFFbK/u22t2jJ4hQ7pT36XVTkAH9Dfd979ilutPo8BnQ+NoWty8jI+fQeBn+H6CQ2Yg12MihdCq1IYS1OhraZbPKO0yiRL/A2V1drBkO32s3vGEfn0Z9m2jpiigWNNg9BrJexquB21t/RxWYcPgYz5lF+ap9HRRwOcEWrh5aTDPs4CTJaHG9cg4qgP7jYr8yEuYcGAo+27q/1HAmjBlPCY/OjHv+ydfTMgjdLJ3trnphEhfZnAweYklTSjBWsFVcJpuum/yikV1PjumlThbX1YoV2G18IASkk0e06XMxjNn08FIFlrujVnTWjhpuiYhSWG6B+8LKUB7BrcaT7nM552LH2uf0ACHoTCjCmGceERZkZXMRAmkTfX3FyDCgSdGpHDlTWFGcSlzMvjcYHO
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
    type: Opaque
