---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgCJKxmNL3ucm183WIyJ930HyK3rjcR1QeFEJC8t6tchK3agqJeP0TNBGYmgX0xVQvohKrmOE+y7RDzu5e7sM8nwH3ZiK0IzvQRwCCOeXYd80SQU4AG8X52MXjPdddwDwdENZ/Y8V+S+cLwZ3Hm77Ucx8PXoKXjKBLBpSz+EOF5Y6dYskSdBxcO72bJxNc/JqQyRGFTjNaa9Yj5tfg+h4tCcU7WcLlq3MNs0OIB6c3WFrDj+/cqCsKYpMq2rBy5RV/ezFYoJlZbPF+tzos2uhctIizLZbBOHWrDNNG0Fp+TVxdymCWKoGvtpBxBu4W3Cmv46qLRKT1Ho9PBQzNhNA2sWPMfoh5XfFQX2K+NuMG6YxFp06nEt/CjXXnRmdTbF7bSlMpOCUfatYvTVa6MHkfUbL1HVDxlmJ+JwIZGiTEit/q5QDIaAz/nrjJCzPXHsSIboIqyTDKQ7tU+Ah2sUjW8q8reo0PtSQxT+6BGg0iWQFQhoIBsl1sSJwJPmRXxcnKrvFs33DiqrZK1u8M7XdK9mSvDs/ocDWEyFf4sI+D+hPJ3ZuwRp68ACSAF8f1AkSfS2+PRBYjIE3GBF12P1LXfkNvPvvVncScbj8yYmm3sut7tviFKd5EIKpUvYWrmcVUfxT5uBbY0N+zhVG5Iv7s/UFFlXeFw64KOLYIi94Q7ojrWEA9nwehLAepyk3PAArBAO4Cx7NJfamVTwPLM5ooM8Yc/kbdZm8CMCupIgOgGhalNZHeoTDkR3
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
