apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-daily
  namespace: cnpg
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
  method: volumeSnapshot
