---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-pg-creds
  namespace: cnpg
spec:
  encryptedData:
    password: AgBUNv4DVn7qo77A8LTXa5CG8lDIcJKY4ye67v51WGTw+0Qmos/XTco8Yt0RGcKsVmdOUrqNtKmsJ04qpfKpsYruBpn/tV1x/9q8R5d74N+9N1/dXesSSqhhtEFbPz5csRDMPE1yiLPz32VmNiiKtRe9R/zRKEJVQjIXaY4fXTeJPRjk1+UK4Ai9vZKW8SxrtdA6vor+N3LtBpuO/UHBgeCttLqirS49WOkdDvF2OMr11Pk7xzvfVf0K2BJzGViP12Z69rrRD/yVreGEqAciGIYqzRcHjhj9ShaxECR41QSYChH4DbCfsZM5ibJvrq62HcazBBp6CkOGgBFe1ODgEpxoFTgfgI0bI/mgGOd3NhpLijMWq3JJsjEiNGTEER9G5qneiIEjSPJnVwmFeZeOOsdsVRUCxGspjXxDBCf9zjXyYJwsAo8S6zrL4vy1zDi8hlJGhRTzd/ta8AEL5G9IYWvbV77iz6WLJA5sIBxhp8nhbeJUGLdIVgdMg6NSEJTJDK/Dgu49GRHuQ+FfyTHbIAY2PPc4ME+1Yiib7L78/yx3ZuLP4pdZ9BbjpFEUKJR2EHcPZsWN9m6JV0G5U0vtr7jSZRT+jYZPFBMl/fEideE5TvzWpM6drB021WJtYVT8mTW8JZmUvQo9ZA/Kq1nztfZjheqbxjGexu8qv6iRTGHA7Dk0IQ7ZlkaEYUd4Mfwlq8XAFlxa3ZYFUkTRdH6aJ3XZF79Tvnp0xIDQ0Va1fk0Z4iutHywHf8gIV4GGTDJiIa5fpzgIJCChS6rTOD6FoncZ
    username: AgDEAtCoRao/LwWgi1x5N8AEudcuUVEYTk5V4KmXj2/wr4APyo2j2g4Qn3gynHRc48Zs/Z3RmWxjFExCmzCJhjLk00Beh7+c5pEDJ8qXNEA+wxVKgGv9JKPZ4ylAjXwxvs71e9bm5SynTp267VNyaTQy6cIcGWZ6dxKMi9Stui629q8VH2TJTDkqG8DovD5P0A3CxvXBjAQBoqxeRQ12Dmh14j5joX3EEty01NID5z/0t6S6IlNMRkVLSoMF0BoMchU+6GfwJtVqQNGXt1zUVTiR665Ype3rfQwUtP7wjH52utmI+SxVaO6c5KFjCLSqDuHqW8y5rBCYws6aMslfB5Df4SA5DoSCs+6iUA7N9Q/YC5WxtMyC9hRnYvOqEVL4ypfcvXsymoDxal/JMvWJ+A5zYkWfZeewQcafV5d/VLe0do5bpq6vrxVdeOkT+FwD/1Rpuf/jOIreJc7aqJAfuBHMjmZYdxTrwsVEl04WyDo7vx/GNJYfQ2YCxCEB6KEo9+Ajxip1As54fHex0qMMTbkeIeDH/PYCjjp9adDDDfAcRIcx7g3q69bD/37sapuusljEcjFb+3Dkdg1JXzeKc9r6gr9hA5otGQ/t2Mc0CbvQujRow+YQFwEB0h0DJ4UbXx2jIFkhNQFfPrshF6FsGQabUWO5xk7Um1UquhjbC2rhQuOhuNCCnmY/AjShxdKXW4kDCDrz0j2EnuKyXA==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: vaultwarden
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: vaultwarden
      name: vaultwarden-pg-creds
      namespace: cnpg
    type: kubernetes.io/basic-auth
