apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: flux-system
spec:
  releaseName: netbird-operator
  targetNamespace: netbird
  interval: 1h
  chart:
    spec:
      chart: netbird-operator
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: netbirdio-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    managementURL: https://netbird.luukblankenstijn.nl
    cluster:
      name: home
