apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: arc-system
spec:
  interval: 5m
  releaseName: gha-runner-scale-set-controller
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      version: "*"
  values:
    authSecret:
      create: false
      name: arc-github-config
