apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: minecraft-voicechat
  namespace: minecraft
spec:
  entryPoints:
    - voicechat-udp
  routes:
    - services:
        - name: minecraft
          port: 24454
